managment.endpoints.web.exposure.include=info
managment.info.env.enabled=true
info.app.name = My First Project
info.pp.description = FunProject
info.app.version = 1.0.0

#Adding custom properties
coach.name = Tom and Jerry
team.name = Tom&Jerry show